# Generated by Django 5.2.1 on 2025-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
