# Generated by Django 5.2.1 on 2025-06-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_review_at_design_review_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the design.'),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_file',
            field=models.FileField(help_text='Upload the design file (PDF, DOCX, etc.).', upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='review_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the design was reviewed.', null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='review_feedback',
            field=models.TextField(blank=True, help_text='Feedback given by the reviewer.'),
        ),
        migrations.AlterField(
            model_name='design',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer who reviewed the design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review status of the design.', max_length=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='title',
            field=models.CharField(help_text='Title of the design.', max_length=255),
        ),
        migrations.AlterField(
            model_name='design',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time the design was uploaded.'),
        ),
        migrations.AlterField(
            model_name='design',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the design.', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
